<?php

/**
 * @file
 * Contains icdc_didomi_embed.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function icdc_didomi_embed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the icdc_didomi_embed module.
    case 'help.page.icdc_didomi_embed':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integration Embed code with Didomi Consent Management Platform.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function icdc_didomi_embed_theme() {
  return [
    'icdc_didomi_embed' => [
      'variables' => ['content' => NULL],
    ],

  ];
}
