<?php

/**
 * @file
 * Contains icdc_social_simple.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;
use Drupal\search_api\Entity\Index;

/**
 * Implements hook_help().
 */
function icdc_social_simple_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the icdc_search module.
    case 'help.page.icdc_social_simple':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module about ICDC social simple shared.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_library_info_alter().
 */
function icdc_social_simple_library_info_alter(&$libraries, $extension) {
  if($extension === 'social_simple') {
    $libraries['buttons']['dependencies'][] = 'icdc_social_simple/buttons';
  }
}
