_core:
  default_config_hash: 71vTnk5szuOQRTsOR-S5bjCzPvkxtx_eVGMqYa_mcqc
langcode: fr
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://cdc.local/themes/custom/cdc_theme/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: themes/custom/cdc_theme/images/logo.png
  url: ''
  use_default: false
schemas:
  bootstrap: 8000
  cdc_theme: 8000
cdn_provider: ''
fluid_container: 1
table_responsive: '-1'
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  breadcrumb: ''
  highlighted: ''
  help: ''
  content_top: ''
  content: ''
  content_bottom: ''
  sidebar_first: ''
  sidebar_second: ''
  footer_top: ''
  footer_first: ''
  footer_second: ''
  footer_third: ''
  hidden: ''
cdn_theme: ''
cdn_cache_ttl_versions: 0
cdn_cache_ttl_themes: 0
cdn_cache_ttl_assets: 0
cdn_cache_ttl_library: 0
reset_http_request_cache: ''
table: ''
breadcrumb_home: 1
forms_required_has_error: 0
modal_enabled: 0
