_core:
  default_config_hash: rHbHZIIF9TP3H2Vs37uCHz4Gm4phULg0rQ_OKihxJfM
langcode: fr
extlink_use_external_js_file: false
extlink_target: true
extlink_target_no_override: true
extlink_nofollow: true
extlink_noreferrer: false
extlink_follow_no_override: true
extlink_subdomains: true
extlink_alert: false
extlink_alert_text: 'Ce lien vous dirige vers un site externe. Nous ne sommes pas responsables de son contenu.'
extlink_exclude: (facebook\.com)|(twitter\.com)|(linkedin\.com)|(viadeo\.com)|(youtube\.com)|(instagram\.com)
extlink_include: ''
extlink_class: ext
extlink_label: '(le lien est externe)'
extlink_img_class: false
extlink_css_exclude: ''
extlink_css_explicit: ''
extlink_mailto_class: mailto
extlink_mailto_label: '(le lien envoie un courriel)'
extlink_use_font_awesome: false
extlink_font_awesome_classes:
  links: 'fa fa-external-link'
  mailto: 'fa fa-envelope-o'
extlink_icon_placement: '0'
whitelisted_domains: {  }
