_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
langcode: fr
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: false
element_name: sujet
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_feedback_form: false
  contact_message_personal_form: false
  node_accueil_form: false
  node_actualite_form: false
  node_article_form: false
  node_blog_form: false
  node_dossier_form: false
  node_gouvernance_form: false
  node_page_form: false
  node_parcours_de_vie_form: false
