_core:
  default_config_hash: MRNY3KucIO38iBurvuzGO7D_P02uiJoWsWordkCvm_k
langcode: fr
preprocess_menus_title: 1
preprocess_menus_language: 1
preprocess_menus_language_list:
  footer: footer
  main: main
  account: '0'
  admin: '0'
  links: '0'
  tools: '0'
