_core:
  default_config_hash: gAO20FzMm9MKfbZTVb8Di5G34KhEzb2wjuGrAKsAF9k
langcode: fr
twitter_feed_api_key: jTUcrC1DCU5ZCs1lROCe3n7sl
twitter_feed_api_secret: h3sfaRbpQFSfLFAZEJuVQPIRU8vC9JJNsZxeoka1BglUOwrSGC
twitter_feed_jquery_timeago_locale: '0'
