<?php

/**
 * @file
 * Contains daterange_formatter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function daterange_formatter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the daterange_formatter module.
    case 'help.page.daterange_formatter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide a formatter for daterange fields') . '</p>';
      return $output;

    default:
  }
}
