/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.miniSitePageDrag = {
    attach: function attach(context, settings) {
      var backStep = settings.mini_sites.backStep;
      var forwardStep = settings.mini_sites.forwardStep;

      var tableDrag = Drupal.tableDrag['mini-site-page'];
      var $table = $('#mini-site-page');
      var rows = $table.find('tr').length;

      tableDrag.row.prototype.onSwap = function (swappedRow) {
        $table.find('tr.mini-site-page-preview').removeClass('mini-site-page-preview');
        $table.find('tr.mini-site-page-divider-top').removeClass('mini-site-page-divider-top');
        $table.find('tr.mini-site-page-divider-bottom').removeClass('mini-site-page-divider-bottom');

        var tableBody = $table[0].tBodies[0];
        if (backStep) {
          for (var n = 0; n < backStep; n++) {
            $(tableBody.rows[n]).addClass('mini-site-page-preview');
          }
          $(tableBody.rows[backStep - 1]).addClass('mini-site-page-divider-top');
          $(tableBody.rows[backStep]).addClass('mini-site-page-divider-bottom');
        }

        if (forwardStep) {
          for (var k = rows - forwardStep - 1; k < rows - 1; k++) {
            $(tableBody.rows[k]).addClass('mini-site-page-preview');
          }
          $(tableBody.rows[rows - forwardStep - 2]).addClass('mini-site-page-divider-top');
          $(tableBody.rows[rows - forwardStep - 1]).addClass('mini-site-page-divider-bottom');
        }
      };
    }
  };
})(jQuery, Drupal);
