name: 'Access Config'
description: 'Composant AccessConfig par Access42. Un sélecteur de styles, léger et open source, pour permettre aux personnes en situation de handicap d’adapter votre site à certains de leurs besoins.'
package: 'Custom'
type: module
version: 1.0
core_version_requirement: ^8 || ^9
