<?php

/**
 * @file
 * Contains icdc_actualites_nav.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function icdc_actualites_nav_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the icdc_actualites_nav module.
    case 'help.page.icdc_actualites_nav':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('ICDC News Navigation block') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function icdc_actualites_nav_theme() {
  return [
    'icdc_actualites_nav' => [
      'variables' => [
        'title' => NULL,
        'prev' => NULL,
        'next' => NULL,
        'prev_url' => NULL,
        'next_url' => NULL,
      ]
    ],
  ];
}
