<?php

namespace Drupal\icdc_toolbox\Plugin\WebformElement;

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Plugin\WebformElement\ManagedFile;

class CustomManagedFile extends ManagedFile {

  public static function processManagedFile(&$element, FormStateInterface $form_state, &$complete_form) {
    $element = parent::processManagedFile($element, $form_state, $complete_form); // TODO: Change the autogenerated stub

    // File placeholder.
    if (!empty($element['#file_placeholder']) && (empty($element['#value']) || empty($element['#value']['fids']))) {
      $element['file_placeholder']['#weight'] = ($element['upload']['#weight'] + 1);
    }

    return $element;
  }

}
